resources:
  start_stop_cycle:
    uuid: "start_stop_cycle"
    version: 1
    name: ["start_stop_cycle"]
    unit: ["bit"]
    topic: "production/cycle/signals/start_stop_cycle/control"
    uri: "production/cycle/signals/start_stop_cycle"
    qos: 2
    retained: False
    frequency: -1

  done_bags:
    uuid: "done_bags"
    version: 1
    name: ["done_bags"]
    unit: ["count"]
    topic: "production/cycle/signals/done_bags/telemetry"
    uri: "production/cycle/signals/done_bags"
    qos: 0
    retained: False
    frequency: 500

  total_bags:
    uuid: "total_bags"
    version: 1
    name: ["total_bags"]
    unit: ["count"]
    topic: "production/cycle/signals/total_bags/control"
    uri: "production/cycle/signals/total_bags"
    qos: 0
    retained: False
    frequency: -1

  placed_objects:
    uuid: "placed_objects"
    version: 1
    name: ["placed_objects"]
    unit: ["count"]
    topic: "production/cycle/signals/placed_objects/telemetry"
    uri: "production/cycle/signals/placed_objects"
    qos: 0
    retained: False
    frequency: 500

  cycle_time:
    uuid: "cycle_time"
    version: 1
    name: ["cycle_time"]
    unit: ["s"]
    topic: "production/cycle/time/telemetry"
    uri: "production/cycle/time"
    qos: 2
    retained: False
    frequency: -1

  current_object:
    uuid: "current_object"
    version: 1
    name: ["current_object"]
    unit: ["B"]
    topic: "production/cycle/signals/current_object/telemetry"
    uri: "production/cycle/signals/current_object"
    qos: 0
    retained: False
    frequency: 500

  selected_recipe:
    uuid: "selected_recipe"
    version: 1
    name: ["selected_recipe"]
    unit: ["B"]
    topic: "production/cycle/recipes/selected_recipe/control"
    uri: "production/cycle/recipes/selected_recipe"
    qos: 0
    retained: False
    frequency: -1

  recipe_objects_types:
    uuid: "recipe_objects_types"
    version: 1
    name: ["type"]
    unit: ["B"]
    topic: "production/cycle/recipes/objects_types/control"
    uri: "production/cycle/recipes/objects_types"
    qos: 1
    retained: False
    frequency: -1

  recipe_end_effector_indexes:
    uuid: "recipe_end_effector_indexes"
    version: 1
    name: ["index"]
    unit: ["count"]
    topic: "production/cycle/recipes/end_effector_indexes/control"
    uri: "production/cycle/recipes/end_effector_indexes"
    qos: 1
    retained: False
    frequency: -1

  recipe_object_types_box_positions:
    uuid: "recipe_object_types_box_positions"
    version: 1
    name: ["recipe_object_types_box_positions"]
    unit: ["list"]
    topic: "production/cycle/recipes/object_types_box_positions/control"
    uri: "production/cycle/recipes/object_types_box_positions"
    qos: 1
    retained: False
    frequency: -1

  recipe_object_types_numbers:
    uuid: "recipe_object_types_numbers"
    version: 1
    name: ["number"]
    unit: ["count"]
    topic: "production/cycle/recipes/object_types_numbers/control"
    uri: "production/cycle/recipes/object_types_numbers"
    qos: 1
    retained: False
    frequency: -1

  cobot_state_cycle:
    uuid: "cobot_state_cycle"
    version: 1
    name: ["cobot_state_cycle"]
    unit: ["B"]
    topic: "cobot/states/cobot_state_cycle/telemetry"
    uri: "cobot/states/cobot_state_cycle"
    qos: 0
    retained: False
    frequency: 500

  robot_mode:
    uuid: "robot_mode"
    version: 1
    name: ["robot_mode"]
    unit: ["count"]
    topic: "cobot/states/robot_mode/telemetry"
    uri: "cobot/states/robot_mode"
    qos: 0
    retained: False
    frequency: 500

  power_on_robot:
    uuid: "power_on_robot"
    version: 1
    name: ["power_on_robot"]
    unit: ["bit"]
    topic: "cobot/states/power_on_robot/telemetry"
    uri: "cobot/states/power_on_robot"
    qos: 0
    retained: False
    frequency: 500

  safety:
    uuid: "safety"
    version: 1
    name: ["safety"]
    unit: ["bit"]
    topic: "cobot/states/safety/telemetry"
    uri: "cobot/states/safety"
    qos: 0
    retained: False
    frequency: 500

  joint_angles:
    uuid: "joint_angles"
    version: 1
    name: ["base", "shoulder", "elbow", "wrist_1", "wrist_2", "wrist_3"]
    unit: ["mrad"]
    topic: "cobot/joints/sensors/angles/telemetry"
    uri: "cobot/joints/sensors/angles"
    qos: 0
    retained: False
    frequency: 500

  joint_angle_velocities:
    uuid: "joint_angle_velocities"
    version: 1
    name: ["base", "shoulder", "elbow", "wrist_1", "wrist_2", "wrist_3"]
    unit: ["mrads"]
    topic: "cobot/joints/sensors/velocities/telemetry"
    uri: "cobot/joints/sensors/velocities"
    qos: 0
    retained: False
    frequency: 500

  joint_current_consumptions:
    uuid: "joint_current_consumptions"
    version: 1
    name: ["base", "shoulder", "elbow", "wrist_1", "wrist_2", "wrist_3"]
    unit: ["mA"]
    topic: "cobot/joints/sensors/current_consumptions/telemetry"
    uri: "cobot/joints/sensors/current_consumptions"
    qos: 0
    retained: False
    frequency: 500

  joint_temperatures:
    uuid: "joint_temperatures"
    version: 1
    name: ["base", "shoulder", "elbow", "wrist_1", "wrist_2", "wrist_3"]
    unit: ["Cel"]
    topic: "cobot/joints/sensors/temperatures/telemetry"
    uri: "cobot/joints/sensors/temperatures"
    qos: 0
    retained: False
    frequency: 500

  tcp:
    uuid: "tcp"
    version: 1
    name: ["x", "y", "z", "rx", "ry", "rz"]
    unit: ["deg", "deg", "deg", "mrad", "mrad", "mrad"]
    topic: "cobot/states/tcp/telemetry"
    uri: "cobot/states/tcp"
    qos: 0
    retained: False
    frequency: 500

  6d_pose_estimation:
    uuid: "6d_pose_estimation"
    version: 1
    name: ["x", "y", "z", "rx", "ry", "rz"]
    unit: ["deg", "deg", "deg", "rad", "rad", "rad"]
    topic: "ai_on_edge/inference/6d_pose_estimation/control/response"
    uri: "ai_on_edge/inference/6d_pose_estimation"
    qos: 2
    retained: False
    frequency: -1

  confidence:
    uuid: "confidence"
    version: 1
    name: ["score"]
    unit: ["%"]
    topic: "ai_on_edge/inference/scores/confidence/telemetry"
    uri: "ai_on_edge/inference/scores/confidence"
    qos: 2
    retained: False
    frequency: -1

  cosine_similarity:
    uuid: "cosine_similarity"
    version: 1
    name: ["score"]
    unit: ["%"]
    topic: "ai_on_edge/inference/scores/cosine_similarity/telemetry"
    uri: "ai_on_edge/inference/scores/cosine_similarity"
    qos: 2
    retained: False
    frequency: -1

  inference_time:
    uuid: "inference_time"
    version: 1
    name: ["inference_time"]
    unit: ["s"]
    topic: "ai_on_edge/inference/time/telemetry"
    uri: "ai_on_edge/inference/time"
    qos: 2
    retained: False
    frequency: -1